### PR TITLE
Fix "Detect "already owned" message and unlock"

### LINKED ISSUE #8: Detect "already owned" message and unlock
A Google Play customer reports that if she purchases on one device and then tries to refresh her 2nd device (using the same Play account), that the new purchase doesn't register for 1-2 days.

However, if she tries to purchase the same volume on the 2nd device, it says: "You already own this".  However, our library doesn't handle this and unlock the volume.

Is there something we can do about this, or are we at the mercy of Google?

### PR DESCRIPTION
**Pull request by AlexDibrivnyy**
- Add missing JvmStatic annotations
- Fix "Detect "already owned" message and unlock" (Close  #8)

### CODE REVIEW

File: library/src/main/java/com/billing/google/GoogleBillingService2.kt [hunk 1]
```diff
@@ -115,8 +115,11 @@ class GoogleBillingService2(val context: Context, private val inAppSkuKeys: List
             }
             BillingClient.BillingResponseCode.USER_CANCELED ->
                 log("onPurchasesUpdated: User canceled the purchase")
-            BillingClient.BillingResponseCode.ITEM_ALREADY_OWNED ->
+            BillingClient.BillingResponseCode.ITEM_ALREADY_OWNED -> {
                 log("onPurchasesUpdated: The user already owns this item")
+                //item already owned? call queryPurchases to verify and process all such items
+                queryPurchases()
+            }
```
Comment (AlexDibrivnyy) [inline library/src/main/java/com/billing/google/GoogleBillingService2.kt:122]: This solution is copied from codelabs.developers.google.com
https://codelabs.developers.google.com/codelabs/play-billing-scalable-kotlin/index.html?index=..%2F..index#3

Idea: let's double-check Google's cache if we receive that type of message and unlock all needed items.

Comment (mikemee) [reply library/src/main/java/com/billing/google/GoogleBillingService2.kt:122]: We tried something similar before. It seemed that the problem was that the local cache was NOT updated, but when the user tried to purchase, it verified on the server and failed because it was already purchased. Customers found that it "fixed itself" in in about 24 hours, but it was frustrating all around until that time passed.

Let's try this and see. I suspect (hope!) that because we've adopted the new API, that Google is much more consistent with this and the cache will now reflect what the server sees more consistently.

**Review by mikemee — APPROVED** [review]
Well done. Let's release this puppy!
